### PR TITLE
SystemAPI Fix Bug

### PR DESCRIPTION
**Pull request by utkucnay**
We don't use SystemAPI in other func SysteamAPI uses Code Gen and Unity don't do this. I changed Tranform2DConversionSystem but i dont know SystemAPI.GetBuffer was important. Other changes is okey in my opinion.

### CODE REVIEW

**Comment by utkucnay** [comment]
I am using Unity version 2022.3.7f1.

**Comment by Antoshidza** [comment]
What bug it fixes?

**Comment by utkucnay** [comment]
image

If you use SystemAPI calls in Funcitions, Entity CodeGen tool throws error. I think we can only to using in OnUpdate, OnCreate like ISytem Functions. I rewrote SystemAPI calls in these functions. That is a bug, right ?

**Comment by Antoshidza** [comment]
Can't reproduce this error, but if it fixes such problems then ok

**Pull request merged**
